### ISSUE TITLE
Cool, but adding s:2->t:3 breaks it

### ISSUE THREAD

**Issue by j2l** [MicLeey/svelte-dependency-viz#1]
Hi, 
I made a change (last edge) and the resulting graph is not what I expected:
```
<script lang="ts">
  import { Graph } from 'svelte-dependency-viz';

  const nodes = [
    { id: 1, name: 'A' },
    { id: 2, name: 'B' },
    { id: 3, name: 'C' }
  ];

  const edges = [
    { source: 1, target: 2 },
    { source: 1, target: 3 },
    { source: 2, target: 3 }
  ];
</script>

<Graph {nodes} {edges} />
```

resulting in:
![image](https://user-images.githubusercontent.com/65325/152142318-524f4b5c-a82d-4800-a3c3-a361384a882e.png)
Is there a fix? Or is it a bug?
Thanks

**Comment by MicLeey** [comment]
Hmm, I didn't plan for this because in this scenario, C depends on B which depends on A. So C implicitly depends on A already.

I could definitely add checks that normalize this for you, but this was a quick and dirty solution to a small problem.

If you agree with the transitive dependency logic, what you probably want is to not explicitly say that C depends on A:

```
  const edges = [
    { source: 1, target: 2 },
    { source: 2, target: 3 }
  ];
```

Produces:
![image](https://user-images.githubusercontent.com/15386836/152177314-dabed46b-2502-45b9-b6a3-5c11428d897a.png)

**Comment by j2l** [comment]
Thank you @MicLeey 
Actually, I was thinking of dependencies in svelte code (components) where A and B can import C.
That's what lead me to this project actually, I was looking for dependencies IN svelte :smile_cat:

**Comment by MicLeey** [comment]
Ha! I'll have to work on the naming in that case :') 

I made this to visualise skill trees on the fly. I'm currently not planning to develop for this use case, but I'd be happy to look at a PR if you want to give it a shot!

You'll likely want to use https://github.com/rollup/rollup/issues/903 and visualize the output instead of using this though :)

**Comment by j2l** [comment]
Sounds good! Thanks
